
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 10
#define YY_END_OF_BUFFER 11
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[38] =
    {   0,
        0,    0,    0,    0,    0,    0,   11,    9,    1,    9,
        4,    5,    1,    4,    4,    3,    1,    0,    0,    0,
        0,    0,    0,    2,    0,    8,    7,    0,    0,    6,
        0,    0,    0,    0,    0,    0,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    6,    7,
        1,    8,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    9,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    9,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[10] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    3,    1
    } ;

static yyconst flex_int16_t yy_base[51] =
    {   0,
        0,    5,   12,    0,   20,   22,   78,   79,   79,   68,
       79,   79,   79,    0,   21,   79,   79,   68,   69,   66,
       23,   65,   64,   79,   65,   79,   79,   32,   21,   79,
       22,   19,    5,    4,    3,    0,   79,   32,   35,   38,
       41,   43,   46,   49,   52,   55,   58,   61,   64,   67
    } ;

static yyconst flex_int16_t yy_def[51] =
    {   0,
       38,   38,   37,    3,   39,   39,   37,   37,   37,   37,
       37,   37,   37,   40,   41,   37,   37,   42,   43,   41,
       41,   44,   42,   37,   45,   37,   37,   46,   44,   37,
       47,   46,   48,   49,   50,   37,    0,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37
    } ;

static yyconst flex_int16_t yy_nxt[89] =
    {   0,
       37,   37,    9,   37,   37,   26,   10,    9,   26,   26,
       26,   10,   11,   12,   13,   14,   11,   11,   15,   11,
       11,    8,   17,    8,   17,   21,   30,   26,   30,   22,
       27,   28,    8,    8,    8,   16,   16,   16,   19,   30,
       19,   20,   20,   23,   23,   23,   25,   25,   25,   29,
       29,   29,   31,   31,   31,   32,   32,   32,   33,   33,
       33,   34,   34,   34,   35,   35,   35,   36,   36,   36,
       26,   24,   30,   27,   26,   24,   18,   37,    7,   37,
       37,   37,   37,   37,   37,   37,   37,   37
    } ;

static yyconst flex_int16_t yy_chk[89] =
    {   0,
        0,    0,    1,    0,    0,   36,    1,    2,   35,   34,
       33,    2,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    5,    5,    6,    6,   15,   32,   31,   29,   15,
       21,   21,   38,   38,   38,   39,   39,   39,   40,   28,
       40,   41,   41,   42,   42,   42,   43,   43,   43,   44,
       44,   44,   45,   45,   45,   46,   46,   46,   47,   47,
       47,   48,   48,   48,   49,   49,   49,   50,   50,   50,
       25,   23,   22,   20,   19,   18,   10,    7,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "get_preamble_ocr.lex"

#line 3 "get_preamble_ocr.lex"
  /*
    1.  retrive preamble labels
    2.  sync_up (num_labels=%d)
    3.  scan_recitals and generate edit list, decide if legit preamble
    4.  create linked list so can add items in the middle
    5.  edit linked list
    CALL: (../bin/get_preamble 0 3968 ../tmp/Index/index_file_3968 localhost dealthing root imaof3 1 < ../tmp/Xxx/aaa7) >& ttt
    CALL:  (../../../dealthing/dtcstuff/bin/get_preamble 0 100 ../../../dealthing/dtcstuff/tmp/Index/index_file_100 localhost dealthing root imaof3 1 < ../../../dealthing/dtcstuff/tmp/Xxx/aaa7) >& ttt

  */

  #include <ctype.h>
  #include <mysql.h>
  #include "entity_functions.h"
  #include "recitals_functions.h"
  FILE *index_file;

  char *db_IP, *db_name, *db_pwd, *db_user_name; // for DB config

  /******************************/
  int debug;
  int do_print;
  int org_id[1];
  char *prog;

  #define MAX_FILE 50
  #define MAX_HEADER 1500
  int max_file_no = 0;
  int max_item_no[MAX_FILE];

  /****************************/

  /************** SQL ********************/
  //  char *server = "localhost";
  /*
  char *server = db_IP; // "54.241.17.226";
  char *user = db_name; // "root";
  char *password = db_pwd; // "imaof3";
  char *database = db_user_name; //"dealthing";
  */
  MYSQL *conn;
  MYSQL_RES *res;
  MYSQL_ROW row;
  /************** END SQL ****************/

  // in reality we do not exceed 1000 in the buffer
#define MAX_VPARA 500 
#define VPARA_SIZE 50000
#define VPARA_SIZE2 100001
  char vpara[VPARA_SIZE];
  char chunk[VPARA_SIZE2]; // store the escaped para
  int doc_id; // input paqram
  int deal_id, oid; // from sql_params

  int pream_no = 0; // how many preams
  int sigblock_no = 0; // how many preams
  int rider_no = 0; // how many preams
  int table_of_contents_no = 0; // how many preams
  int recitals_no = 0; // how many preams

  int pid = 0;
  char *make_norm_vpara(char *text);

  int sql_region(char vpara[], int doc_id, char *rtype, int score, char *recitals_feature) { // rtype 0 NA, 1 now_therefore (the beginning of the bus part of the doc
    return 0;
    #define INTEGER 5
    #define TEXT 3
    #define COMPLEX 2

    int complex_id_name[1];

    int complex_id = insert_complex_field(conn, doc_id, deal_id, org_id[0], pid, rtype, complex_id_name,score,2,rtype,1);

    char chunk[1000];
    mysql_real_escape_string(conn,chunk,vpara,strlen(vpara));

    static char rtype_field[60];
    sprintf(rtype_field,"%s_field",rtype);
    //insert_text_field(conn,doc_id, deal_id, org_id[0],pid, complex_id, complex_id_name[0], rtype_field, chunk, 1, TEXT, score);

    int fid = insert_any_field(conn,"text",doc_id, deal_id, org_id[0],pid, complex_id, complex_id_name[0], rtype_field, "NA", chunk, 1, score,"text");

    if (recitals_feature && strlen(recitals_feature)) {
      insert_recitals_feature(conn, recitals_feature, fid, doc_id, deal_id, org_id[0]);
    }

    return 0;
  } // sql_region()

  int print_vpara() {
    char *norm_vpara = make_norm_vpara(vpara);
    static char pream_words[2000];
    static char sigblock_words[2000];
    static char rider_words[2000];
    static char table_of_contents_words[2000];
    static char recitals_words[2000];

    int preamble_score = 0;
    int sigblock_score = 0;
    int rider_score = 0;
    int table_of_contents_score = 0;
    int recitals_score = 0;

    /*********************************  PREAMBLE ****************************************/
    strcpy(pream_words,"");
    if (strcasestr(norm_vpara,"made") ) {
      strcat(pream_words,"made, ");
      preamble_score++;
    }

    if (strcasestr(norm_vpara,"entered") ) {
      strcat(pream_words,"entered, ");
      preamble_score++;
    }

    if (strcasestr(norm_vpara,"entered into") ) {
      strcat(pream_words,"entered into, ");
      preamble_score += 2;
    }

    if (strcasestr(norm_vpara,"having an office") ) {
      strcat(pream_words,"having an office, ");
      preamble_score += 2;
    }

    if (strcasestr(norm_vpara,"with offices at") ) {
      strcat(pream_words,"with offices at, ");
      preamble_score += 2;
    }

    if (strcasestr(norm_vpara,"with principal offices at") ) {
      strcat(pream_words,"with principal offices at, ");
      preamble_score += 2;
    }

    if (strcasestr(norm_vpara,"principal place of business") ) {
      strcat(pream_words,"principal place of business, ");
      preamble_score += 2;
    }

    if (strcasestr(norm_vpara,"located at") ) {
      strcat(pream_words,"located at, ");
      preamble_score += 2;
    }

    if (strcasestr(norm_vpara,"all capitalized") ) {
      strcat(pream_words,"all capitalized, ");
      preamble_score += 2;
    }

    if (strcasestr(norm_vpara,"Amendment") ) {
      strcat(pream_words,"Amendment, ");
      preamble_score += 1;
    } 

    if (strcasestr(norm_vpara,"Addendum") ) {
      strcat(pream_words,"Addendum, ");
      preamble_score += 1;
    } 

    if (strcasestr(norm_vpara,"amends") ) {
      strcat(pream_words,"amends, ");
      preamble_score += 1;
    } 

    if (strstr(norm_vpara,"Effective Date") ) {
      strcat(pream_words,"Effective Date, ");
      preamble_score += 2;
    } else if (strcasestr(norm_vpara,"Effective Date") ) {
      strcat(pream_words,"Effective Date, ");
      preamble_score += 1;
    }

    if (strcasestr(norm_vpara,"incorporated under") ) {
      strcat(pream_words,"incorporated under, ");
      preamble_score += 1;
    }

    if (strcasestr(norm_vpara,"limited liability company") ) {
      strcat(pream_words,"limited liability company, ");
      preamble_score += 1;
    }

    if (strcasestr(norm_vpara,"LLC") ) {
      strcat(pream_words,"LLC, ");
      preamble_score += 1;
    }

    if (strstr(norm_vpara,"INC") ) {
      strcat(pream_words,"INC, ");
      preamble_score += 1;
    } else if (strstr(norm_vpara,"Inc") ) {
      strcat(pream_words,"Inc, ");
      preamble_score += 1;
    }


    if (strcasestr(norm_vpara,"collectively") ) {
      strcat(pream_words,"collectively, ");
      preamble_score += 1;
    }

    if (strcasestr(norm_vpara,"day of ") ) {
      strcat(pream_words,"day of, ");
      preamble_score += 1;
    }

    if (strcasestr(norm_vpara,"corporation") ) {
      strcat(pream_words,"corporation, ");
      preamble_score += 1;
    }

    if (strcasestr(norm_vpara,"hereinafter") ) {
      strcat(pream_words,"hereinafter, ");
      preamble_score += 1;
    }

    if (strcasestr(norm_vpara,"behalf") ) {
      strcat(pream_words,"behalf, ");
      preamble_score += 2;
    }

    if (strcasestr(norm_vpara,"subsidiaries") ) {
      strcat(pream_words,"subsidiaries, ");
      preamble_score += 2;
    }

    if (strcasestr(norm_vpara,"affiliates") ) {
      strcat(pream_words,"affiliates, ");
      preamble_score += 2;
    }

    if (strcasestr(norm_vpara,"agree as follows") ) {
      strcat(pream_words,"agree as follows, ");
      preamble_score += 2;
    }

    if (strcasestr(norm_vpara,"hereby agree as follows") ) {
      strcat(pream_words,"hereby agree as follows, ");
      preamble_score += 4;
    }

    if (strcasestr(norm_vpara,"between") ) {
      strcat(pream_words,"between, ");
      preamble_score++;
    }

    if (strcasestr(norm_vpara,"herein") ) {
      strcat(pream_words,"herein, ");
      preamble_score++;
    }

    if (strcasestr(norm_vpara,"dated") ) {
      strcat(pream_words,"dated, ");
      preamble_score++;
    }
    if (strcasestr(norm_vpara,"among") ) {
      strcat(pream_words,"among, ");
      preamble_score++;
    }
    if (strcasestr(norm_vpara,"agreement")/* ||strcasestr(norm_vpara,"lease") || strcasestr(norm_vpara,"rider") || strcasestr(norm_vpara,"indenture")  */) {
      strcat(pream_words,"agreement, ");
      preamble_score++;
    }
    if (strcasestr(norm_vpara,"amendment") || strcasestr(norm_vpara,"addendum") ) {
      strcat(pream_words,"amendment, ");
      preamble_score++;
    }

    if (strcasestr(norm_vpara," by and between") ) {
      strcat(pream_words,"by and between, ");
      preamble_score += 2;
    }

    if (strcasestr(norm_vpara,"entered into") ) {
      strcat(pream_words,"entered into, ");
      preamble_score += 2;
    }

    if (strcasestr(norm_vpara," as of ") ) {
      strcat(pream_words,"as of, ");
      preamble_score++;
    }

    if (strcasestr(norm_vpara," effective ") ) {
      strcat(pream_words,"effective, ");
      preamble_score++;
    }

    if (strcasestr(norm_vpara,"made") ) {
      strcat(pream_words,"made, ");
      preamble_score++;
    }

    if (strstr(norm_vpara,"This ") ) {
      strcat(pream_words,"This, ");
      preamble_score += 2;
    }

    if (strstr(norm_vpara,"THIS ") ) {
      strcat(pream_words,"THIS, ");
      preamble_score += 2;
    }

    if (strcasestr(norm_vpara,"letter of intent") ) {
      strcat(pream_words,"letter of intent, ");
      preamble_score++;
    }

    if (strcasestr(norm_vpara,"statement of work") ) {
      strcat(pream_words,"statement of work, ");
      preamble_score++;
    }

    if (strcasestr(norm_vpara,"statement of services") ) {
      strcat(pream_words,"statement of services, ");
      preamble_score++;
    }

    if (strcasestr(norm_vpara,"sow") ) {
      strcat(pream_words,"sow, ");
      preamble_score++;
    }

    if (strstr(norm_vpara,"In connection") ) {
      strcat(pream_words,"In connection, ");
      preamble_score += 2;
    }

    if (strstr(norm_vpara,"In consideration") ) {
      strcat(pream_words,"In consideration, ");
      preamble_score += 2;
    }

    /***********************************************/

    if (strcasestr(norm_vpara,"sos") ) {
      strcat(pream_words,"sos, ");
      preamble_score++;
    }

    if (strcasestr(norm_vpara,"Miscellaneous") ) {
      strcat(pream_words,"*miscellaneous*, ");
      preamble_score -=2;
    }

    if (strcasestr(norm_vpara,"Termination") ) {
      strcat(pream_words,"*termination*, ");
      preamble_score -=2;
    }

    if (strcasestr(norm_vpara,"MISCELLANEOUS") ) {
      strcat(pream_words,"*miscellaneous*, ");
      preamble_score -= 6;
    }

    if (strcasestr(norm_vpara,"governing law") ) {
      strcat(pream_words,"*governing law*, ");
      preamble_score -= 3;
    }

    if (strcasestr(norm_vpara,"definitive agreement") ) {
      strcat(pream_words,"*definitive agreement*, ");
      preamble_score -= 3;
    }

    if (strcasestr(norm_vpara,"jurisdiction") ) {
      strcat(pream_words,"*jurisdiction*, ");
      preamble_score -= 3;
    }

    if (strcasestr(norm_vpara,"arbitration") ) {
      strcat(pream_words,"*arbitration*, ");
      preamble_score -= 3;
    }

    if (strcasestr(norm_vpara,"construed") ) {
      strcat(pream_words,"*construed*, ");
      preamble_score -= 2;
    }

    if (strcasestr(norm_vpara,"shall mean") || strcasestr(norm_vpara,"means") ) {
      strcat(pream_words,"*shall mean*, ");
      preamble_score -= 2;
    }

    if (strcasestr(norm_vpara,"governed") ) {
      strcat(pream_words,"*governed*, ");
      preamble_score -= 2;
    }

    if (strcasestr(norm_vpara,"controlled") ) {
      strcat(pream_words,"*controlled*, ");
      preamble_score -= 2;
    }

    if (strcasestr(norm_vpara,"no agency") ) {
      strcat(pream_words,"*governed*, ");
      preamble_score -= 2;
    }

    if (strcasestr(norm_vpara,"entire agreement") ) {
      strcat(pream_words,"*entire agreement*, ");
      preamble_score -= 2;
    }

    if (strstr(norm_vpara,"WHEREAS")||strstr(norm_vpara,"Whereas") ) {
      preamble_score -= 10;
    }

    if (strstr(norm_vpara,"THEREFORE")) {
      preamble_score -= 10;
    }

    //if (debug) fprintf(stderr,"PREAM33: i=%d: p=%d: s=%d: l=%d: w=%s:\n  p=%s:BBB\n", pream_no,pid,preamble_score,strlen(norm_vpara),pream_words,vpara);
    if (preamble_score > 2 
	&& no_good_array[pid] == 0 // what is this??
	&& pream_no < 25) {  // don't give me too many preams
      if (debug) fprintf(stderr,"PREAM5: i=%d:  no_good=%d: p=%d: score=%d: l=%d: w=%s:\n  p=%s:BBB\n", pream_no,no_good_array[pid],pid,preamble_score,strlen(norm_vpara),pream_words,vpara);
      pream_no++;
      sql_region(vpara, doc_id, "Preamble", preamble_score,NULL);
    } else {
      if (debug) fprintf(stderr,"NO PREAM5: i=%d:  no_good=%d: p=%d: score=%d: l=%d: w=%s:\n  p=%s:BBB\n", pream_no,no_good_array[pid], pid,preamble_score,strlen(norm_vpara),pream_words,vpara);
    }
    strcpy(pream_words,"");

    /*********************************  SIGBLOCK ****************************************/
    if (strcasestr(norm_vpara,"in witness whereof") ) {
      strcat(sigblock_words,"in witness whereof, ");
      sigblock_score += 10;
    }

    if (strcasestr(norm_vpara,"signatures follow") || (strcasestr(norm_vpara,"signatures") && strcasestr(norm_vpara,"follow") && strcasestr(norm_vpara,"page"))) {
      sigblock_score += 10;
    }

    if (strcasestr(norm_vpara,"AGREED AND ACCEPTED") || (strcasestr(norm_vpara,"ACCEPTED") && strcasestr(norm_vpara,"AGREED"))) {
      strcat(sigblock_words,"agreed, ");
      sigblock_score += 10;
    }

    if (strstr(norm_vpara,"Whereof") || strstr(norm_vpara,"WHEREOF") ) {
      strcat(sigblock_words,"whereof, ");
      sigblock_score += 10;
    }

    if (strcasestr(norm_vpara,"Witnesseth") == NULL && (strstr(norm_vpara,"Witness") || strstr(norm_vpara,"WITNESS"))) {
      strcat(sigblock_words,"witness, ");
      sigblock_score += 10;
    }

    if (strcasestr(norm_vpara,"AGREED AND ACCEPTED") || (strcasestr(norm_vpara,"ACCEPTED") && strcasestr(norm_vpara,"AGREED"))) {
      strcat(sigblock_words,"agreed, ");
      sigblock_score += 10;
    }

    if (sigblock_score > 5 
	&& no_good_array[pid] == 0
	&& sigblock_no < 5) { 
      if (debug) fprintf(stderr,"SIGBLOCK:  i=%d: p=%d: c=%d: l=%d: w=%s:\n  p=%s\n", sigblock_no,pid,sigblock_score,strlen(norm_vpara),sigblock_words,vpara);
      sigblock_no++;
      mysql_real_escape_string(conn,chunk,vpara,strlen(vpara)); // we might be running it twice for the same para.  No big deal
      sql_region(vpara, doc_id, "Sigblock", sigblock_score,NULL);
    }

    /*********************************  RIDER ****************************************/
    if (strstr(norm_vpara,"RIDER")) {
      strcat(rider_words,"Rider, ");
      rider_score += 10;
    }

    if (rider_score > 5 
	&& no_good_array[pid] == 0
	&& rider_no < 5) { 
      if (debug) fprintf(stderr,"RIDER:  i=%d: p=%d: c=%d: l=%d: w=%s:\n  p=%s\n", rider_no,pid,rider_score,strlen(norm_vpara),rider_words,vpara);
      rider_no++;
      mysql_real_escape_string(conn,chunk,vpara,strlen(vpara)); // we might be running it twice for the same para.  No big deal
      sql_region(vpara, doc_id, "Rider", rider_score,NULL);
    }


    /*********************************  TABLE_OF_CONTENTS ****************************************/

    if ((strstr(norm_vpara,"TABLE") && strstr(norm_vpara,"CONTENTS")) ||  strcasestr(norm_vpara,"TABLE OF CONTENTS")) {
      strcat(table_of_contents_words,"table_of_contents, ");
      table_of_contents_score = 10;
    }

    if (strstr(norm_vpara,"INDEX")) {
      strcat(table_of_contents_words,"index, ");
      table_of_contents_score += 15;
    }

    if (strstr(norm_vpara,"EXHIBITS")) {
      strcat(table_of_contents_words,"EXHIBITS, ");
      table_of_contents_score += 15;
    }

    if (strcasestr(norm_vpara,"LIST OF EXHIBITS")) {
      strcat(table_of_contents_words,"list_of_exhibits, ");
      table_of_contents_score += 15;
    }
    if (table_of_contents_score > 5 
	&& no_good_array[pid] == 0
	&& table_of_contents_no < 5) { 
      if (debug) fprintf(stderr,"TABLE_OF_CONTENTS:  i=%d: p=%d: c=%d: l=%d: w=%s:\n  p=%s\n", table_of_contents_no,pid,table_of_contents_score,strlen(norm_vpara),table_of_contents_words,vpara);
      table_of_contents_no++;
      mysql_real_escape_string(conn,chunk,vpara,strlen(vpara)); // we might be running it twice for the same para.  No big deal
      sql_region(vpara, doc_id, "Table_Of_Contents", table_of_contents_score,NULL);
    }
    /*********************************  RECITALS ****************************************/
    char *recitals_feature = NULL;
    if (0 &&(strcasestr(norm_vpara,"WITNESSETH") || strcasestr(norm_vpara,"W I T N E S S E T H") )) { // dropped since witnesses alone causes problem in DOLLAR GEN LSE
      strcat(recitals_words,"WITNESSETH, ");
      recitals_score += 10;
      recitals_feature = "WITNESSETH";;
    }

    if (strcasestr(norm_vpara,"whereas") || strcasestr(norm_vpara,"w h e r e a s") ) {
      strcat(recitals_words,"whereas, ");
      recitals_score += 10;
      recitals_feature = "WHEREAS";;
    }


    if (strcasestr(norm_vpara,"FOR AND IN CONSIDERATION") || strcasestr(norm_vpara,"IN CONSIDERATION") ) {
      strcat(recitals_words,"consideration, ");
      recitals_score += 5;
      recitals_feature = "CONSIDERATION";;
    }

    if (strcasestr(norm_vpara,"the parties agree as follows") ) {
      strcat(recitals_words,"the parties agree as follows, ");
      recitals_score += 10;
      recitals_feature = "AGREE";
    } else if (strcasestr(norm_vpara,"hereby agree as follows") ) {
      strcat(recitals_words,"hereby agree as follows, ");
      recitals_score += 10;
      recitals_feature = "AGREE";
    } else if (strcasestr(norm_vpara," agree as follows") ) {
      strcat(recitals_words," agree as follows, ");
      recitals_score += 5;
      recitals_feature = "AGREE";
    }

    char *pp1 = strcasestr(norm_vpara,"NOW");
    char *pp2;
    if (pp1) {
      pp2 = strcasestr(norm_vpara,"THEREFORE");
    }
    if (pp1 && pp2) {
      strcat(recitals_words,"now therefore, ");
      recitals_score += 10;
      recitals_feature = "NOW_THEREFORE";
    }

    if (strcasestr(norm_vpara,"Recitals") || strcasestr(norm_vpara,"R e c i t a l s") ) {
      strcat(recitals_words,"recitals, ");
      recitals_score += 10;
      recitals_feature = "RECITALS";
    }

    if (strstr(norm_vpara,"BACKGROUND") || strstr(norm_vpara,"Background") ) {
      strcat(recitals_words,"background, ");
      recitals_score += 10;
      recitals_feature = "BACKGROUND";
    }

    if (recitals_score > 5 
	&& no_good_array[pid] == 0
	&& recitals_no < 100) { 
      if (debug) fprintf(stderr,"RECITALS: i=%d: p=%d: s=%d: l=%d: w=%s:\n  p=%s\n", recitals_no,pid,recitals_score,strlen(norm_vpara),recitals_words,vpara);
      recitals_no++;
      mysql_real_escape_string(conn,chunk,vpara,strlen(vpara));
      sql_region(vpara, doc_id, "Recitals", recitals_score,recitals_feature);
    }

    strcpy(recitals_words,"");
    /****************************************************************************/
    strcpy(vpara,"");
    return 0;
  } //print_vpara()
#line 1061 "<stdout>"

#define INITIAL 0
#define in_para 1
#define in_para_start 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 591 "get_preamble_ocr.lex"

#line 1247 "<stdout>"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 38 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 79 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 592 "get_preamble_ocr.lex"
;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 594 "get_preamble_ocr.lex"
{
  BEGIN in_para_start; strcpy(vpara,"");
  
  char *pp = strstr(yytext,"sn=\"");
  if (pp) {
    pid = atoi(pp+4);
  } else {
    pp = strstr(yytext,"id=\"");
    if (pp) {
      pid = atoi(pp+4);
    }
  }
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 609 "get_preamble_ocr.lex"
{
  BEGIN in_para;
  yyless(0);
 }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 614 "get_preamble_ocr.lex"
if (strlen(vpara) < MAX_VPARA) strcat(vpara,yytext);
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 616 "get_preamble_ocr.lex"
if (strlen(vpara) < MAX_VPARA) strcat(vpara," ");
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 618 "get_preamble_ocr.lex"
{ 
  BEGIN 0; yyless(0); print_vpara();
}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 622 "get_preamble_ocr.lex"
if (strlen(vpara) < MAX_VPARA) strcat(vpara," ");
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 623 "get_preamble_ocr.lex"
if (strlen(vpara) < MAX_VPARA) strcat(vpara," ");
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 624 "get_preamble_ocr.lex"
;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 625 "get_preamble_ocr.lex"
ECHO;
	YY_BREAK
#line 1403 "<stdout>"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(in_para):
case YY_STATE_EOF(in_para_start):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 38 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 38 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 37);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 625 "get_preamble_ocr.lex"



char *make_norm_vpara(char text[]) {
  int ii;
  int jj;
  static char bext[20000];
  int first = 1; // first non_alnum
  for (jj = 0, ii = 0; ii < strlen(text); ii++) {
    if (isalnum(text[ii])) {
      bext[jj++] = text[ii];
      first = 1;
    } else {
      if (first == 1) {
	bext[jj++] = ' ';
	first = 0;
      } else {
	;
      }
    }
  } // for
  bext[jj++] = '\0';
  return bext;
}

int doc_name_abstract() {
  MYSQL_RES *sql_res;
  MYSQL_ROW sql_row;

  static char query[500];
  char *doc_name = NULL;
  sprintf(query,"select name \n\
                     from deals_document \n	\
                     where \n\
                       id = '%d' ",
	  doc_id
	  );

  if (debug) fprintf(stderr,"QUERY00 (%s): query=%s:\n",prog,query);
  if (mysql_query(conn, query)) {
    fprintf(stderr,"%s\n",mysql_error(conn));
    fprintf(stderr,"QUERY00 (%s): query=%s:\n",prog,query);
  }
  
  sql_res = mysql_store_result(conn);
  int nn = mysql_num_rows(sql_res);
  if (nn > 0) {
    sql_row = mysql_fetch_row(sql_res);
    doc_name = sql_row[0];
  }
  int is_abstract = strcasestr(doc_name,"abstract") ? 1 : 0;
  int is_finance = (strstr(doc_name,"CCR")
		    || strcasestr(doc_name,"recon"))
		    ? 1 : 0;

  // S/B UPDATE instead of REPLACE/ AVI is setting docinfo earlier
  sprintf(query,"select * \n\
                     from deals_docinfo \n\
                     where \n\
                       doc_id = '%d' ",
	  doc_id
	  );

  if (debug) fprintf(stderr,"QUERY01 (%s): query=%s:\n",prog,query);
  if (mysql_query(conn, query)) {
    fprintf(stderr,"%s\n",mysql_error(conn));
    fprintf(stderr,"QUERY01 (%s): query=%s:\n",prog,query);
  }

  sql_res = mysql_store_result(conn);
  nn = mysql_num_rows(sql_res);
  if (0) {
  if (nn != 0) {
    sprintf(query,"replace \n\
                     into deals_docinfo \n\
                     set \n\
                       organization_id = '%d' \n\
                       , is_abstract = '%d' \n\
                       , is_finance = '%d' \n\
                       , doc_id = '%d' "
	  , org_id[0], is_abstract, is_finance, doc_id);

    if (debug) fprintf(stderr,"QUERY02 (%s): query=%s:\n",prog,query);
    if (mysql_query(conn, query)) {
      fprintf(stderr,"%s\n",mysql_error(conn));
      fprintf(stderr,"QUERY02 (%s): query=%s:\n",prog,query);
    }

    fprintf(stderr,"Error: DOCINFO not found for doc=%d: \n",doc_id);
  } else {
    sprintf(query,"update \n\
                     deals_docinfo \n\
                     set \n\
                       organization_id = '%d' \n\
                       , is_abstract = '%d' \n\
                       , is_finance = '%d' \n\
                       , last_update_date = now() \n\
	             where \n\
                       doc_id = '%d' "
	  , org_id[0], is_abstract, is_finance, doc_id);

    if (debug) fprintf(stderr,"QUERY03 (%s): query=%s:\n",prog,query);
    if (mysql_query(conn, query)) {
      fprintf(stderr,"%s\n",mysql_error(conn));
      fprintf(stderr,"QUERY03 (%s): query=%s:\n",prog,query);
    }
  }
  }

  return 0;
}


int main(int ac, char **av) {
  prog = av[0];
  do_print = 0;
  if (ac != 9) {
    fprintf(stderr,"Error: %s takes (8) print_out, doc_id, index_file, db_IP, db_name, db_user_name, db_pwd, debug (got %d params)\n",av[0],ac);
    exit(0);
  }
  fprintf(stderr,"Info: %s got po=%s: doc_id:%s: index_name=%s: IP=%s: name=%s: user_name=%s: pwd=%s: debug=%s:\n",av[0],av[1],av[2],av[3],av[4],av[5],av[6], av[7], av[8]);
  do_print= atoi(av[1]);
  doc_id = atoi(av[2]);
  index_name = av[3];
  db_IP = av[4];
  db_name = av[5];
  db_user_name = av[6]; // for DB config
  db_pwd = av[7];
  debug_entity = my_debug = debug = atoi(av[8]);
  conn = mysql_init(NULL);
  //debug_entity = my_debug = debug = 0; // for now
  /* now connect to database */
  if (!mysql_real_connect(conn,db_IP,db_user_name,db_pwd,db_name,0,NULL,0)) {
    fprintf(stderr,"%s\n",mysql_error(conn));
    exit(1);
  }

  deal_id = get_did_oid(conn,doc_id, org_id);

  doc_name_abstract(); // add doc properties based on doc name

  delete_recitals_feature(conn, doc_id); // delete recitals_feature which extends recitals

  delete_complex_field(conn,doc_id,"preamble"); // remove old inserts
  delete_complex_field(conn,doc_id,"sigblock"); // remove old inserts
  delete_complex_field(conn,doc_id,"rider"); // remove old inserts
  delete_complex_field(conn,doc_id,"table_of_contents"); // remove old inserts
  delete_complex_field(conn,doc_id,"recitals"); // remove old inserts

  index_file = fopen(index_name,"r"); 
  if (!index_file) {
    fprintf(stderr,"Error: can't (r) open index_file %s\n",index_name);
    exit(0);
  }
  if (debug) fprintf(stderr,"STEP 0: %s read index\n",av[0]);    
  index_array_no = read_index(index_file); // read the index into index_array
  if (my_debug) fprintf(stderr,"INDEX_ARRAY_NO=%d:\n",index_array_no);
  yylex();

  fprintf(stderr,"Info: %s done (%d preams, %d recitals):\n",av[0],pream_no,recitals_no);

  if (debug) fprintf(stderr,"STEP 1: %s retrieve pream_labels\n",av[0]);  

  int num_labels = get_recitals_from_sql(conn, doc_id); // STEP 1

  if (debug) fprintf(stderr,"STEP 2: %s sync_up (num_labels=%d)\n",av[0],num_labels);  

  sync_up_recitals_and_toc(); // STEP 2

  if (debug) fprintf(stderr,"\n\n\n\nSTEP 3: %s create linked list\n\n\n\n",av[0]);  
  create_linked_list_index(index_array_no); // create a linked list so can add items in the middle // STEP 4 //F07

  if (debug) fprintf(stderr,"\n\n\n\nSTEP 4: %s scan_recitals and generate edit list\n\n\n\n",av[0]);  

  edit_index_array_no = scan_recitals_from_array(edit_index_array); // STEP 3: decide if legit preamble
  if (debug) fprintf(stderr,"FOUND %d PREAMs\n",edit_index_array_no);
  if (debug) fprintf(stderr,"Opened (r) index_file %s\n",index_name);


  if (debug) fprintf(stderr,"\n\n\n\nSTEP 5: %s edit linked list\n\n\n\n",av[0]);  

  /* int new_in =*/ modify_index(edit_index_array_no); // add items for preamble // STEP 5: generate the new entry in the index // F08
  insert_parts_into_sql(conn,doc_id); // F09
  write_index(index_array_no); // write out the modified index // STEP 6: print out //F10

  return 0;
}

